"""
Generic Job Output Watcher for LYRN.

Monitors job_output/ for completions generated by model_runner.py,
detects when generation finishes, and forwards the response file to
scripts/parse_job_response.py for structural validation and affordance chaining.
"""

import os
import sys
import time
import argparse
import subprocess
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def main():
    parser = argparse.ArgumentParser(description="LYRN Job Output Watcher")
    parser.add_argument("--job", required=True, help="Job in Category/JobName format")
    parser.add_argument("--retry-count", type=int, default=0, help="Current retry count")
    parser.add_argument("--timeout", type=int, default=90, help="Watcher timeout in seconds")

    args = parser.parse_args()

    parts = args.job.split("/")
    if len(parts) < 2:
        print(f"[JobOutputWatcher] Error: Invalid job format '{args.job}'. Expected Category/JobName.")
        sys.exit(1)

    category, job_name = parts[0], parts[1]
    output_dir = PROJECT_ROOT / "job_output"
    output_dir.mkdir(parents=True, exist_ok=True)

    status_file = PROJECT_ROOT / "global_flags" / "llm_status.txt"

    start_time = time.time()
    print(f"[JobOutputWatcher] Monitoring for output of '{category}/{job_name}' (retry={args.retry_count})...")

    # Keep track of existing files to detect new ones
    existing_files = {p.name: p.stat().st_mtime for p in output_dir.glob("*.txt")}

    seen_busy = False
    detected_file = None

    while (time.time() - start_time) < args.timeout:
        # Check LLM status
        current_status = "idle"
        if status_file.exists():
            try:
                current_status = status_file.read_text(encoding="utf-8").strip()
            except Exception:
                pass

        if current_status == "busy":
            seen_busy = True

        # Check for newly created or modified files in job_output/
        current_files = list(output_dir.glob("*.txt"))
        new_or_modified = []
        for p in current_files:
            mtime = p.stat().st_mtime
            if p.name not in existing_files or mtime > existing_files[p.name]:
                new_or_modified.append((p, mtime))

        if new_or_modified:
            # Sort newest first
            new_or_modified.sort(key=lambda x: x[1], reverse=True)
            candidate = new_or_modified[0][0]

            # If the LLM has transitioned back to idle, or if the file was updated and size is stable
            if (seen_busy and current_status == "idle") or (not seen_busy and candidate.stat().st_size > 0):
                # Wait a brief moment to ensure file write buffer flushed
                time.sleep(0.5)
                detected_file = candidate
                break

        time.sleep(0.5)

    if not detected_file:
        print(f"[JobOutputWatcher] Timeout waiting for output file from '{category}/{job_name}'.")
        sys.exit(1)

    print(f"[JobOutputWatcher] Detected completion output: {detected_file.name}")

    # Invoke parse_job_response.py
    parse_script = PROJECT_ROOT / "scripts" / "parse_job_response.py"
    if parse_script.exists():
        cmd = [
            sys.executable,
            str(parse_script),
            "--category", category,
            "--job-name", job_name,
            "--response-file", str(detected_file),
            "--retry-count", str(args.retry_count),
        ]
        print(f"[JobOutputWatcher] Executing parser: {' '.join(cmd)}")
        res = subprocess.run(cmd)
        sys.exit(res.returncode)
    else:
        print(f"[JobOutputWatcher] Error: Parser script not found at {parse_script}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
